MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.36"
PostSources: posts/*
AllPosts: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ToList()
IsPost: => Context.GetDocumentList("AllPosts").ContainsById(Document)
AllTags: => Context.GetDocumentList("AllPosts").SelectMany(post => post.GetList<string>("Tags")).Distinct().ToList()