MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.36"
SiteTitle: Sonic Hub 官方網站
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? $"{siteTitle} | 首頁" : $"{siteTitle} | {title}");
  }
SiteAuthor: Sonic Hub
SiteAuthorTitle: Community
SiteDescription: 是一個使用繁體中文交流的索尼克粉絲社群。
PostSources: posts/*
AllPosts: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ToList()
IsPost: => Context.GetDocumentList("AllPosts").ContainsById(Document)
PageSources: pages/*
AllPages: => Context.Outputs.FilterSources(Context.GetString("PageSources")).ToList()
IsPage: => Context.GetDocumentList("AllPages").ContainsById(Document)
AllTags: => Context.GetDocumentList("AllPosts").SelectMany(post => post.GetList<string>("Tags")).Distinct().ToList()
GitHubOwner: "SonicHubTW"
GitHubName: "sonichubtw.github.io"
GitHubToken: => Config.FromSetting<string>("GITHUB_TOKEN")
